version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      production-deps:
        patterns: ['*']
        exclude-patterns: ['@types/*']
      dev-deps:
        dependency-type: development
        patterns: ['*']
